// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
typedef SWIFT_ENUM(NSInteger, InbEndpoint) {
  InbEndpointProduction = 0,
  InbEndpointTesting = 1,
};

typedef SWIFT_ENUM(NSInteger, InbLogLevel) {
  InbLogLevelVerbose = 0,
  InbLogLevelDebug = 1,
  InbLogLevelInfo = 2,
  InbLogLevelWarning = 3,
  InbLogLevelError = 4,
  InbLogLevelSevere = 5,
  InbLogLevelNone = 6,
};

@class UILocalNotification;
@class UNNotification;
@class NSNumber;
@class NSError;

SWIFT_CLASS("_TtC11InbeaconSdk11InbeaconSdk")
@interface InbeaconSdk : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) InbeaconSdk * _Nonnull sharedInstance;)
+ (InbeaconSdk * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(InbeaconSdk * _Nonnull)value;
+ (InbeaconSdk * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (void)setClientID:(NSString * _Nonnull)clientId andClientSecret:(NSString * _Nonnull)clientSecret;
+ (InbeaconSdk * _Nonnull)createWithClientID:(NSString * _Nonnull)clientId andClientSecret:(NSString * _Nonnull)clientSecret SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)refreshWithForce:(BOOL)force;
- (void)refresh;
- (BOOL)didReceiveLocalNotification:(UILocalNotification * _Nonnull)notification;
- (BOOL)didReceiveUserNotification:(UNNotification * _Nonnull)notification SWIFT_AVAILABILITY(ios,introduced=10.0);
/// <hr/>
/// \code
///  * Setters / Getters
///
/// \endcode
@property (nonatomic, copy) NSString * _Nullable IDFA;
@property (nonatomic) enum InbLogLevel logLevel;
- (NSString * _Nullable)userStringForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSNumber * _Nullable)userNumberForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)setUserString:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
- (void)setUserNumber:(NSNumber * _Nonnull)value forKey:(NSString * _Nonnull)key;
- (BOOL)userHasTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (void)userSetTag:(NSString * _Nonnull)tag;
- (void)userResetTag:(NSString * _Nonnull)tag;
- (void)setSettingString:(NSString * _Nonnull)setting ToValue:(NSString * _Nonnull)val;
- (void)setSettingInt:(NSString * _Nonnull)setting ToValue:(NSInteger)val;
- (void)setSetting:(NSString * _Nonnull)setting val:(id _Nonnull)val;
- (NSString * _Nullable)settingForKey:(NSString * _Nonnull)setting SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)setting:(NSString * _Nonnull)setting SWIFT_WARN_UNUSED_RESULT;
- (void)setEndpoint:(enum InbEndpoint)endpoint;
- (NSError * _Nullable)checkCapabilitiesAndRights SWIFT_WARN_UNUSED_RESULT;
- (void)checkCapabilitiesAndRightsWithAlert;
- (void)modalclickWithClosebar:(BOOL)doclosebar doUpperThird:(BOOL)doUpperThird;
@end


@interface NSNumber (SWIFT_EXTENSION(InbeaconSdk))
@end


@interface UIDevice (SWIFT_EXTENSION(InbeaconSdk))
@end

#pragma clang diagnostic pop
